### ISSUE TITLE
No such file or directory: 'nanopore_test_compressed.bsc.tmp.dir/recon.bin'

### ISSUE THREAD

**Issue by bellstwohearted** [shubhamchandak94/LFZip#3]
I installed the tool using conda, while I run
```
python nlms_compress.py -m c -i ../data/evaluation_datasets/dna/nanopore_test.npy -o nanopore_test_compressed.bsc -a 0.01
```
I was informed
```
/bin/sh: 1: /root/LFZip/src/nlms_helper.out: not found
Traceback (most recent call last):
  File "/root/LFZip/src/nlms_compress.py", line 109, in <module>
    with open(tmpfile_recon, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'nanopore_test_compressed.bsc.tmp.dir/recon.bin'
```

How can I fix this??

**Comment by shubhamchandak94** [comment]
Hi,
As mentioned in the README [here](https://github.com/shubhamchandak94/LFZip#compressiondecompression), you should replace python nlms_compress.py by lfzip-nlms when you are using conda, otherwise it will use the local file while the code has been installed elsewhere in the conda path.
Regards,
Shubham

**Comment by bellstwohearted** [comment]
> Hi,
> As mentioned in the README [here](https://github.com/shubhamchandak94/LFZip#compressiondecompression), you should replace python nlms_compress.py by lfzip-nlms when you are using conda, otherwise it will use the local file while the code has been installed elsewhere in the conda path.
> Regards,
> Shubham

Thanks for the quick response. It works~

**Comment by shubhamchandak94** [comment]
Great!
